from __future__ import annotations

from typing import Protocol


class MarketSignalProvider(Protocol):
    def get_market_share(self, **filters) -> list[dict]: ...
    def get_competitors(self, **filters) -> list[dict]: ...
    def get_pricing(self, **filters) -> list[dict]: ...
    def get_opportunity(self, **filters) -> list[dict]: ...

